Bump watermark-photo

diff --git a/bin/watermark-photo b/bin/watermark-photo
--- a/bin/watermark-photo
+++ b/bin/watermark-photo
@@ -10,22 +10,44 @@ function drop-extension() {
 }
 
 function uppercase() {
-    tr 'a-z' 'A-Z'
+    tr '[:lower:]' '[:upper:]'
+}
+
+function get-exif-date() {
+    local FORMAT="$1"
+    local INPUT_FILE="$2"
+    exiv2 -g 'Exif.Photo.DateTimeOriginal' -Pv "$INPUT_FILE" |
+        cut -d' ' -f1 |
+        xargs date -j -f'%Y:%m:%d' "$FORMAT"
+}
+
+function get-exif-title() {
+    local INPUT_FILE="$1"
+    exiv2 -g 'Exif.Photo.UserComment' -Pt "$INPUT_FILE"
 }
 
 function main() {
-    local TITLE="$(echo "$1" | uppercase)"
-    local INPUT_FILE="$2"
+    local INPUT_FILE="$1"
     local OUTPUT_FILE="$(drop-extension "$INPUT_FILE").jpg"
     local EXV_FILE="$(drop-extension "$INPUT_FILE").exv"
     local FONT="/System/Library/Fonts/Helvetica.dfont" # Or convert -list font
-    local DATE="$(date '+%B %Y' | uppercase)"
+    local TITLE="$(get-exif-title "$INPUT_FILE" | uppercase)"
+    local DATE="$(get-exif-date '+%B %Y' "$INPUT_FILE" | uppercase)"
+
+    # Check title
+    if [[ "$TITLE" = "" ]]; then
+        echo "Missing title in user-comment field"
+        exit 1
+    fi
 
     # Check extension
     if [[ "$(take-extension "$INPUT_FILE")" != "tif" ]]; then
         echo "Input file should be a TIF"
         exit 1
     fi
+
+    # Remove XMP packet and preview from input file
+    exiv2 -d xt "$INPUT_FILE"
 
     # Dump EXIF to "$INPUT_FILE".exv
     exiv2 ex "$INPUT_FILE"
@@ -50,7 +72,7 @@ function main() {
         -draw "text 10,6 '$TITLE'"               \
         -gravity NorthEast                       \
         -draw "text 10,6 '$DATE'"                \
-        -quality 95                              \
+        -quality 98                              \
         "$INPUT_FILE"                            \
         "$OUTPUT_FILE"
 
@@ -62,9 +84,10 @@ function main() {
 }
 
 # Check number of arguments
-if [[ $# != 2 ]]; then
-    echo "Usage: $0 'Your Title' picture.tif"
+if [[ $# != 1 ]]; then
+    echo "Usage: $0 picture.tif"
+    echo "The user-comment exiv2 field must be set to the title."
     exit 1
 fi
 
-main "$1" "$2"
+main "$1"
